title: "PyFun Notes"
description: "feedId:170421468079292416+userId:125808254043183104"
baseurl: "" 
url: "https://pycat.site/"
locale: "zh-CN"

author:
  name: "Dan"
  email: "liwbeijing@gmail.com"
  bio: "AI、芯片、产品"
  avatar: "https://avatars.githubusercontent.com/u/17510239?v=4"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/danliustc"

remote_theme: "mmistakes/minimal-mistakes"

# RSS Feed 优化配置
feed:
  posts_limit: 20                    # RSS中显示的文章数量
  excerpt_only: false                # 显示完整文章内容，不仅仅是摘要
  path: /feed.xml                    # RSS feed路径

# RSS 额外配置
rss:
  site_description: "AI、芯片、产品相关技术博客"  # RSS feed描述
  site_author: "Dan"                 # 站点作者
  site_language: "zh-CN"             # 站点语言
  site_copyright: "2025 Dan"         # 版权信息

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

minimal_mistakes_skin: "default"

include:
  - "_pages"

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Dan"
      author_profile: true
      read_time: false
      comments: false
      share: true
