title: "PyFun Notes"
description: "AI、芯片、产品思考｜写给未来的同行"
baseurl: "" 
url: "https://pycat.site/"
locale: "zh-CN"

# author:
#  name: "Dan"
#  email: "liwbeijing@gmail.com"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

include:
  - "_pages"

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Dan"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
